FROM node:18


RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app


COPY package*.json ./
RUN npm install

RUN pip3 install --break-system-packages torch==2.1.0 numpy==1.24.3
RUN pip3 install --break-system-packages torch-geometric

COPY . .

RUN mkdir -p models

EXPOSE 5001
CMD ["node", "server.js"]